/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * xFiltro.java
 *
 * Created on Jan 4, 2012, 12:46:23 PM
 */
package com.jswitch.reporte.vista;

import com.jswitch.base.controlador.logger.LoggerUtil;
import com.jswitch.base.modelo.HibernateUtil;
import com.jswitch.reporte.controlador.ReporteController;
import com.jswitch.reporte.modelo.ParametroReporte;
import com.jswitch.reporte.modelo.Reporte;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JDialog;
import org.hibernate.classic.Session;
import org.openswing.swing.mdi.client.MDIFrame;

/**
 *
 * @author Personal
 */
public class xFiltro extends JDialog {

    Calendar calendar = Calendar.getInstance();
    Reporte reporte;

    /** Creates new form xFiltro */
    public xFiltro(Reporte reporte) {
        super(MDIFrame.getInstance(), true);
        initComponents();
        this.reporte = reporte;
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();

        setTitle("Filtro");

        jLabel1.setText("Mes");

        jLabel2.setText("Año");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(calendar.get(Calendar.MONTH+1), 1, 12, 1));

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(calendar.get(Calendar.YEAR), 2000, calendar.get(Calendar.YEAR), 1));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jSpinner1, jSpinner2});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList<ParametroReporte> parametrosFiltro = new ArrayList<ParametroReporte>();
        parametrosFiltro.add(new ParametroReporte("Año", "", "" + jSpinner2.getValue()));
        parametrosFiltro.add(new ParametroReporte("Mes", "", "" + jSpinner1.getValue()));
        Session s = null;
        try {
            s = HibernateUtil.getSessionFactory().openSession();
            String sql=reporte.getBaseSQL();
            //sql+= "WHERE ";
            List dataSource = s.createQuery(sql).list();
            new ReporteController().mostrarReporte(dataSource, parametrosFiltro, reporte.getFile(), reporte.getTitulo(), "Estilo3.jrtx");
        } catch (Exception ex) {
            LoggerUtil.error(this.getClass(), "showReport", ex);
        } finally {
            s.close();
        }


        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    // End of variables declaration//GEN-END:variables
}
